Fix possible typo with `gnupg-curl` vs `gnupg curl`
Installing just `gnupg-curl` causes this issue:
```
Setting up ca-certificates (20170717~16.04.2) ...
Setting up krb5-locales (1.13.2+dfsg-5ubuntu2.1) ...
Setting up libsasl2-modules:amd64 (2.1.26.dfsg1-14ubuntu0.1) ...
Setting up gnupg-curl (1.4.20-1ubuntu3.3) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for ca-certificates (20170717~16.04.2) ...
Updating certificates in /etc/ssl/certs...
148 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
 * ERROR: Failed to run install_ubuntu_stable_deps()!!!
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
 * DEBUG: Removing the temporary apt error file /tmp/apt_error.n3jI
ERROR: Service 'ubuntu-16-tester' failed to build: The command '/bin/sh -c /tmp/bootstrap-salt.sh -X -d -D' returned a non-zero code: 1
```

Where as installing both `gnupg` and `curl` ensures `install_ubuntu_stable_deps` runs correctly, as a sub-dependency of `curl` looks to be missing.
```
Setting up ca-certificates (20170717~16.04.2) ...
Setting up krb5-locales (1.13.2+dfsg-5ubuntu2.1) ...
Setting up libsasl2-modules:amd64 (2.1.26.dfsg1-14ubuntu0.1) ...
Setting up curl (7.47.0-1ubuntu2.13) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for ca-certificates (20170717~16.04.2) ...
Updating certificates in /etc/ssl/certs...
148 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
OK
```

I suspect this is a typo, because looking at the code line above, `__PACKAGES="${__PACKAGES} gnupg dirmngr"`, that installs two packages.