fix(arch): remove `python2-futures` package (moved to AUR)
The `stable latest` build in the `salt-image-builder` started failing.

* https://gitlab.com/myii/salt-image-builder/-/jobs/1124156923

```
error: target not found: python2-futures
 core is up to date
 extra is up to date
 community is up to date
 * ERROR: Failed to run install_arch_linux_stable()!!!
```

The package has been moved to AUR:

* https://aur.archlinux.org/packages/python2-futures/
* https://aur.archlinux.org/cgit/aur.git/commit/?h=python2-futures&id=06dea3ff2267d052dbc3779c9a93d31766769c6b
  - `import from community`

The build is passing again with this workaround applied using `sed`:

* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/commit/83efb01cb8d12bfed121b003233afc7000300f06
* https://gitlab.com/myii/salt-image-builder/-/jobs/1124687557