fix install_arch_linux_git_deps python2-setuptools is the correct package
:: python2-setuptools and python2-distribute are in conflict
(setuptools). Remove python2-distribute? [y/N] error: unresolvable
package conflicts detected
error: failed to prepare transaction (conflicting dependencies)

:: python2-setuptools and python2-distribute are in conflict